import { cn } from "@/lib/utils";
import { ReactQueryClientProvider } from "@/providers/react-query-client-provider";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
	title: "Imageine",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={cn("bg-background antialiased min-h-screen")}>
				<ReactQueryClientProvider>{children}</ReactQueryClientProvider>
			</body>
		</html>
	);
}
