import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";
import LenisProvider from "@/providers/lenis-provider";
import { ReactQueryClientProvider } from "@/providers/react-query-client-provider";
import { SearchStoreProvider } from "@/providers/search-store-provider";
import type { Metadata } from "next";
import "./globals.css";
import { validateRequest } from "@/lib/auth";
import SessionProvider from "@/providers/session-provider";

export const metadata: Metadata = {
	title: "Imageine",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await validateRequest();

	return (
		<html lang="en">
			<body className={cn("bg-background antialiased min-h-screen relative")}>
				<ReactQueryClientProvider>
					<SessionProvider value={session}>
						<SearchStoreProvider>
							<LenisProvider>{children}</LenisProvider>
							<Toaster />
						</SearchStoreProvider>
					</SessionProvider>
				</ReactQueryClientProvider>
			</body>
		</html>
	);
}
